terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

# --- 0. SECRETS & VARIABLES ---

variable "openai_api_key" {
  description = "OpenAI API Key for the AI Agent"
  type        = string
  sensitive   = true
}


variable "gmail_user" {
  description = "Gmail username for sending notifications"
  type        = string
  sensitive   = true
}

variable "gmail_app_pass" {
  description = "Gmail App Password for secure email sending"
  type        = string
  sensitive   = true
}

variable "manager_email" {
  description = "Email address of the manager"
  type        = string
  sensitive   = true
}

variable "alpaca_api_key" {
  description = "Alpaca API Key for trading operations"
  type        = string
  sensitive   = true
}

variable "alpaca_secret_key" {
  description = "Alpaca Secret Key for trading operations"
  type        = string
  sensitive   = true
}

variable "groq_api_key" {
  description = "Groq API Key for querying data"
  type        = string
  sensitive   = true
}

variable "alpha_vantage_api_key" {
  description = "Alpha Vantage API Key for market data"
  type        = string
  sensitive   = true
}


# --- 1. SECURITY GROUP (Firewall) ---
resource "aws_security_group" "trading_bot_sg" {
  name        = "trading-bot-security-group"
  description = "Allow inbound traffic for FastAPI and SSH"

  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    from_port   = 8000
    to_port     = 8000
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

# --- 2. BACKEND: EC2 INSTANCE ---
data "aws_ami" "ubuntu" {
  most_recent = true
  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"]
  }
  owners = ["099720109477"] # Canonical's AWS Account ID
}

resource "aws_instance" "backend_server" {
  ami                    = data.aws_ami.ubuntu.id
  instance_type          = "t3.micro"
  vpc_security_group_ids = [aws_security_group.trading_bot_sg.id]

  user_data = <<-EOF
              #!/bin/bash
              apt-get update -y
              # Install dependencies: curl for uv, git for repo, python for app
              apt-get install -y curl python3-pip python3-venv git
              
              # Install uv (which provides the 'uvx' command needed by MCP)
              curl -LsSf https://astral.sh/uv/install.sh | sh
              
              git clone https://github.com/LOKI-25/Autonomous-Agentic-Trading-Bot.git /app
              cd /app

              # Securely create the .env file with all variables
              echo "GMAIL_USER=${var.gmail_user}" > .env
              echo "GMAIL_APP_PASS=${var.gmail_app_pass}" >> .env
              echo "MANAGER_EMAIL=${var.manager_email}" >> .env
              echo "ALPACA_API_KEY=${var.alpaca_api_key}" >> .env
              echo "ALPACA_SECRET_KEY=${var.alpaca_secret_key}" >> .env
              echo "GROQ_API_KEY=${var.groq_api_key}" >> .env
              echo "OPENAI_API_KEY=${var.openai_api_key}" >> .env
              echo "ALPHA_VANTAGE_API_KEY=${var.alpha_vantage_api_key}" >> .env

              python3 -m venv venv
              source venv/bin/activate
              pip install -r requirements.txt
              export PATH="/root/.local/bin:$PATH" # Add uv to the PATH for the uvicorn process
              nohup uvicorn servers.risk_gatekeeper.admin_dashboard:app --host 0.0.0.0 --port 8000 > backend.log 2>&1 &
              EOF

  tags = {
    Name = "TradingBot-Backend"
  }
}

# --- 3. FRONTEND: S3 STATIC WEBSITE ---
resource "aws_s3_bucket" "frontend_bucket" {
  bucket = "trading-bot-frontend-dashboard-12345" # MUST be globally unique across all of AWS!
  force_destroy = true
}

resource "aws_s3_bucket_public_access_block" "frontend_public_access" {
  bucket = aws_s3_bucket.frontend_bucket.id
  block_public_acls       = false
  block_public_policy     = false
  ignore_public_acls      = false
  restrict_public_buckets = false
}

resource "aws_s3_bucket_website_configuration" "frontend_website" {
  bucket = aws_s3_bucket.frontend_bucket.id
  index_document { suffix = "index.html" }
  error_document { key = "index.html" }
}

resource "aws_s3_bucket_policy" "frontend_public_policy" {
  bucket = aws_s3_bucket.frontend_bucket.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid       = "PublicReadGetObject"
        Effect    = "Allow"
        Principal = "*"
        Action    = "s3:GetObject"
        Resource  = "${aws_s3_bucket.frontend_bucket.arn}/*"
      },
    ]
  })
}

# --- 5. AUTOMATIC FRONTEND CONFIGURATION ---
resource "local_file" "angular_environment" {
  content  = <<-EOT
// This file is automatically generated by Terraform!
export const environment = {
  production: true,
  apiUrl: 'http://${aws_instance.backend_server.public_ip}:8000'
};
EOT
  filename = "${path.module}/frontend/dashboard-ui/src/environments/environment.prod.ts"
}

# --- 4. OUTPUTS ---
output "backend_api_url" {
  value = "http://${aws_instance.backend_server.public_ip}:8000"
}
output "frontend_website_url" {
  value = aws_s3_bucket_website_configuration.frontend_website.website_endpoint
}